/* DO NOT EDIT THIS FILE!!!  It has been generated for your pleasure. */
// deno-lint-ignore-file 

import { assert, assertObjectMatch } from 'https://deno.land/std@0.162.0/testing/asserts.ts'
import { DataTypeAdapter } from '../../streams/dataTypeAdapter.ts'
import { isCopyBothResponse, parseBackendMessage, CopyBothResponse } from '../messageFormats.generated.ts'
import { MessageWriterAdapter } from '../messageWriterAdapter.ts'
import { NamedTypedValue } from '../ITypedValue.ts'
import { WriteReadTester } from '../../streams/WriteReadTester.ts'
import { fromEntries } from '../fromEntries.ts'

Deno.test('write/read CopyBothResponse', async () => {
    const message: NamedTypedValue[] = [{"type":"Char","value":"W","name":"messageType"},{"type":"Int32","value":4125163520,"name":"length"},{"type":"Int8","value":21,"name":"isBinary"},{"sizeType":"Int16","value":[{"type":"Int16","value":41824},{"type":"Int16","value":13815},{"type":"Int16","value":32768}],"name":"formatCodes"}]
    const expectedRead = fromEntries(message) as Record<string, unknown>

    const writeReadTester = new WriteReadTester()
    let messageWriterAdapter: MessageWriterAdapter | null = null
    let dataTypeAdapter: DataTypeAdapter | null = null

    try {
        messageWriterAdapter = new MessageWriterAdapter(writeReadTester.writable)
        await messageWriterAdapter.writeMessage(message)
        dataTypeAdapter = new DataTypeAdapter(writeReadTester.readable)
        const actualRead = (await parseBackendMessage(dataTypeAdapter)) as unknown as Record<string, unknown>

        assert(isCopyBothResponse(actualRead as unknown as CopyBothResponse), `typeGuard: isCopyBothResponse failed`)

        delete expectedRead.length
        delete actualRead.length

        assertObjectMatch(actualRead, expectedRead)
        assertObjectMatch(expectedRead, actualRead)
    } finally {
        messageWriterAdapter?.release()
        dataTypeAdapter?.release()
    }
})

/* DO NOT EDIT THIS FILE!!!  It has been generated for your pleasure. */
