import { writeFileSync } from 'https://deno.land/std@0.161.0/node/fs.ts'
import { formats, IMessageField, IMessageFormat } from './formats.ts'
import { TypeInfo } from './typeInfo.ts'
import { ITextCompiler } from '../../compilers/ITextCompiler.ts'
import { Region } from '../../structures/Region.ts'
import { TextCompiler } from '../../compilers/TextCompiler.ts'
import { Import } from '../../components/Import.ts'
import { Interface } from '../../components/Interface.ts'
import { Function_ } from '../../components/Function_.ts'
import { Parameter } from '../../components/Parameter.ts'
import { ParameterList } from '../../components/ParameterList.ts'

const validateStartup = () => {
    const cwd = Deno.cwd()
    if (!cwd.endsWith('simple_pg_client')) {
        throw new Error(`Generation script should be run from project root.\n  cwd: ${cwd}`)
    } else {
        console.log(`[validateStartup] cwd: ${cwd}`)
    }
}

validateStartup()

//#region globals
const builtinsFileName = 'builtinTypes'
const warning = `/* DO NOT EDIT THIS FILE!!!  It has been generated for your pleasure. */`

export type TBuiltinTypeInfo = { jsType: string; adapterType: string }

//prettier-ignore
export const builtinTypes: { [type: string]: TBuiltinTypeInfo } = {
    Int32:  { jsType: 'number',     adapterType: 'Int32' },
    Int16:  { jsType: 'number',     adapterType: 'Int16' },
    Int8:   { jsType: 'number',     adapterType: 'Int8' },
    Byte:   { jsType: 'number',     adapterType: 'Int8' },
    Byte1:  { jsType: 'string',     adapterType: 'Char' },
    Byte4:  { jsType: 'number[]',   adapterType: 'Byte4' },
    String: { jsType: 'string',     adapterType: 'String' },
    // Char:   { jsType: 'string',   adapterType: 'Char'   }, // no longer used...
}

//#endregion

//#region imports

const imports_ = {
    DataTypeAdapter: new Import(['DataTypeAdapter'], '../streams/dataTypeAdapter.ts'),
    MessageWriterAdapter: new Import(['DataTypeAdapter'], '../streams/dataTypeAdapter.ts'),
    builtins: new Import(
        [...Object.keys(builtinTypes), ...Object.keys(builtinTypes).map(t => `parse${t}`)],
        `./${builtinsFileName}.generated.ts`
    ),
}

//#endregion

//#region builtins

// prettier-ignore
const builtinFunction_ = (name: string) => new Function_(
    `parse${name}`,
    new ParameterList([new Parameter('adapter', 'DataTypeAdapter')]),
    `Promise<${name}>`
).with(
    { export_: true, arrow_: true, const_: true, expressionBody_: true, }
)

const genBuiltins2 = (compiler: ITextCompiler) => {
    // TODO: Fix me!
    // compiler.writeImports(['DataTypeAdapter'], '../streams/dataTypeAdapter.ts').newLine()
    compiler.embed(imports_.DataTypeAdapter) //(['DataTypeAdapter'], '../streams/dataTypeAdapter.ts').newLine()

    const fnDefInfo: [Function_, () => void][] = []
    for (const name of Object.keys(builtinTypes)) {
        const { jsType, adapterType } = builtinTypes[name]
        compiler.writeType(name, jsType, { export_: true })
        // prettier-ignore
        fnDefInfo.push([
            builtinFunction_(name),
            () => { compiler.writeLine(`adapter.read${adapterType}()`) }
        ])
    }
    compiler.newLine()
    for (const info of fnDefInfo) compiler.writeFunction_(...info)
    compiler.newLine()
}

//#endregion

//#region interfaces

const getInterface: (format: IMessageFormat) => Interface = format => {
    const properties: InterfacePropertyOptions[] = []
    for (const property of format.definition) {
        properties.push({
            name: property.name,
            type: new TypeInfo(property.type).tsType,
            comment: property.definition,
        })
    }
    return new Interface(format.title, properties).with({ export_: true })
}

//#endregion

//#region Parsers

//#endregion

const genFile2 = (fileName: string, writeFile: (compiler: ITextCompiler) => void) => {
    const path = `./src/messages/${fileName}.generated.ts`
    console.log(`[genFile2] Generating file ${fileName} ...`)
    const compiler = new TextCompiler()
    writeFile(compiler)
    /// FILE
    const file = `${warning}\n${compiler.compile()}\n${warning}`
    writeFileSync(path, file)
    console.log(`[genFile2] Generating file ${fileName} complete`)
}

// genFile2(builtinsFileName, genBuiltins2)

genFile2('genTesting', compiler => {
    writeImports(compiler)
    compiler.build(new Region('INTERFACES'), () => {
        for (const format of formats) {
            const interface_ = getInterface(format)
            interface_.write(compiler)
        }
    })
})
