/* DO NOT EDIT THIS FILE!!!  It has been generated for your pleasure. */
// deno-lint-ignore-file 

import {
    DataTypeAdapter,
} from '../streams/dataTypeAdapter.ts'

export type Int32 = number
export type Int16 = number
export type Int8 = number
export type Byte = number
export type Byte1 = string
export type Byte4 = number[]
export type String = string
export type KVPairs = [string, string][]

export const parseInt32: (adapter: DataTypeAdapter) => Promise<Int32> = (adapter) => adapter.readInt32()
export const parseInt16: (adapter: DataTypeAdapter) => Promise<Int16> = (adapter) => adapter.readInt16()
export const parseInt8: (adapter: DataTypeAdapter) => Promise<Int8> = (adapter) => adapter.readInt8()
export const parseByte: (adapter: DataTypeAdapter) => Promise<Byte> = (adapter) => adapter.readInt8()
export const parseByte1: (adapter: DataTypeAdapter) => Promise<Byte1> = (adapter) => adapter.readChar()
export const parseByte4: (adapter: DataTypeAdapter) => Promise<Byte4> = (adapter) => adapter.readByte4()
export const parseString: (adapter: DataTypeAdapter) => Promise<String> = (adapter) => adapter.readString()
export const parseKVPairs: (adapter: DataTypeAdapter) => Promise<KVPairs> = (adapter) => adapter.readKVPairs()
/* DO NOT EDIT THIS FILE!!!  It has been generated for your pleasure. */
