/* DO NOT EDIT THIS FILE!!!  It has been generated for your pleasure. */

import { DataTypeAdapter } from '../streams/dataTypeAdapter.ts'

export type Int32 = number;
export type Int16 = number;
export type Int8 = number;
export type Byte = number;
export type Byte1 = string;
export type Char = string;
export type String = string;

export const parseInt32 = (adapter: DataTypeAdapter) => adapter.readInt32();
export const parseInt16 = (adapter: DataTypeAdapter) => adapter.readInt16();
export const parseInt8 = (adapter: DataTypeAdapter) => adapter.readInt8();
export const parseByte = (adapter: DataTypeAdapter) => adapter.readInt8();
export const parseByte1 = (adapter: DataTypeAdapter) => adapter.readChar();
export const parseChar = (adapter: DataTypeAdapter) => adapter.readChar();
export const parseString = (adapter: DataTypeAdapter) => adapter.readString();

/* DO NOT EDIT THIS FILE!!!  It has been generated for your pleasure. */