import { ITextCompiler } from './compilers/ITextCompiler.ts'
import { TextCompiler } from './compilers/TextCompiler.ts'
import { TComponent } from './compilers/TComponent.ts'

import { Comment } from './components/Comment.ts'
import { IWriter } from './components/IWriter.ts'
import { Import } from './components/Import.ts'

import { Configurable } from './Configurable.ts'
import { Dependencies } from './Dependencies.ts'

const warning = `/* DO NOT EDIT THIS FILE!!!  It has been generated for your pleasure. */`

export interface FileGeneratorOptions {
    generationWarning: string
    lintIgnores: string[]
    imports: Import[]
    components: TComponent[]
}

export class FileGenerator extends Configurable<FileGeneratorOptions> implements IWriter {
    constructor(public name: string, public outputDirectory: string) {
        super({
            generationWarning: warning,
            lintIgnores: [],
            imports: [],
            components: [],
        })
    }

    write(compiler: ITextCompiler): ITextCompiler {
        if (this.options.components.length === 0)
            throw new Error(`FileGenerator for (${this.outputPath}) has no body - this is likely an error`)
        return compiler
            .writeLine(this.options.generationWarning)
            .writeLine(new Comment([`deno-lint-ignore-file ${this.options.lintIgnores.join(' ')}`]))
            .writeLines(...this.options.imports)
            .writeLines(...this.options.components)
            .writeLine(this.options.generationWarning)
    }

    get outputPath(): string {
        return `${this.outputDirectory}/${this.name}.generated.ts`
    }

    emit(): void {
        console.log(`[FileGenerator.emit] Generating file ${this.outputPath} ...`)
        const data = new TextCompiler().write(this).compile()
        Dependencies.writeTextFileSync(this.outputPath, data)
        console.log(`[FileGenerator.emit] complete`)
    }
}
